#!/usr/bin/env bash
# moshrc is an alternative to sshrc for mosh users


function moshrc() {
    local SSHHOME=${SSHHOME:=~}
    if [ -f $SSHHOME/.sshrc ]; then
        local files=.sshrc
        if [ -d $SSHHOME/.sshrc.d ]; then
            files="$files .sshrc.d"
        fi
        SIZE=$(tar cfz - -h -C $SSHHOME $files | wc -c)
        if [ $SIZE -gt 65536 ]; then
            printf >&2 '.sshrc.d and .sshrc files must be less than 64kb\ncurrent size: %s bytes\n' "$SIZE"
            exit 1
        fi
        mosh "$@" -- /bin/bash -c "
            command -v openssl >/dev/null 2>&1 || { printf >&2 \"sshrc requires openssl to be installed on the server, but it's not. Aborting.\\n\"; exit 1; }
            if [ -e /etc/motd ]; then cat /etc/motd; fi
            if [ -e /etc/update-motd.d ]; then run-parts /etc/update-motd.d/; fi
            export SSHHOME=\$(mktemp -d -t .$(whoami).sshrc.XXXX)
            export SSHRCCLEANUP=\$SSHHOME
            trap \"rm -rf \$SSHRCCLEANUP; exit\" 0
            printf %s '$(<"$0" openssl enc -base64)' | openssl enc -base64 -d > \$SSHHOME/moshrc
            chmod +x \$SSHHOME/moshrc

            printf %s '$( openssl enc -base64 << 'EOF'
if [ -e /etc/bash.bashrc ]; then source /etc/bash.bashrc; fi
if [ -e ~/.bashrc ]; then source ~/.bashrc; fi
source $SSHHOME/.sshrc;
export PATH=$PATH:$SSHHOME
EOF
)' | openssl enc -base64 -d > \$SSHHOME/sshrc.bashrc

            printf %s '$( openssl enc -base64 << 'EOF'
#!/usr/bin/env bash
exec bash --rcfile <(printf %s '
if [ -e /etc/bash.bashrc ]; then source /etc/bash.bashrc; fi
if [ -e ~/.bashrc ]; then source ~/.bashrc; fi
source '$SSHHOME'/.sshrc;
export PATH=$PATH:'$SSHHOME'
') "$@"
EOF
)' | openssl enc -base64 -d > \$SSHHOME/bashsshrc
            chmod +x \$SSHHOME/bashsshrc

            printf %s '$(tar czf - -h -C $SSHHOME $files | openssl enc -base64)' | openssl enc -base64 -d | tar mxzf - -C \$SSHHOME
            export SSHHOME=\$SSHHOME
            bash --rcfile \$SSHHOME/sshrc.bashrc
            "
    else
        printf 'No such file: %s\n' "$SSHHOME/.sshrc" >&2
    fi
}
if [ "$1" ]; then
    command -v openssl >/dev/null 2>&1 || { printf >&2 "sshrc requires openssl to be installed locally, but it's not. Aborting.\\n"; exit 1; }
    moshrc "$@"
else
    mosh
fi
